security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AuthAuthenticator
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true

      logout:
        path: app_logout
        target: app_login
      entry_point: App\Security\AuthAuthenticator

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: true

  access_control:
    - { path: ^/login }
    - { path: ^/logout, roles: ROLE_USER }
    - { path: ^/registration, roles: ROLE_USER }
    - { path: ^/ }
