index:
  path: /
  controller: App\Controller\DefaultController::index

app_login:
  path: /login
  controller: App\Controller\UserController::login

app_logout:
  path: /logout
  controller: App\Controller\UserController::logout

app_registration:
  path: /registration
  controller: App\Controller\RegistrationController::index

guest_new:
  path: /guest/new
  controller: App\Controller\GuestController::new

guest_edit:
  path: /guest/{id}/edit
  controller: App\Controller\GuestController::edit

api_endpoint:
  path: /api/endpoint
  controller: App\Controller\ApiController::index
  methods: [POST]